# Generated by Django 3.1.7 on 2021-03-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20210301_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img_src',
            field=models.TextField(blank=True, null=True),
        ),
    ]
