# Generated by Django 3.1.7 on 2021-03-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_auto_20210301_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.discussion'),
        ),
    ]
